export const sampleResponseWithChannelsAndPlaylists = {
  pageInfo: {
    totalResults: 33781,
    resultsPerPage: 25,
  },
  regionCode: "UA",
  nextPageToken: "CBkQAA",
  items: [
    {
      id: "17DMmMyc",
      image: "https://i.ytimg.com/vi/8ONz3_vjJIY/mqdefault.jpg",
      channelTitle: "The Psychedelic Muse",
      channelId: "UCAepXw94EhaO0CZV9f5D3fQ",
      itemId: "8ONz3_vjJIY",
      name: "Sync24 - Omnious [Full Album]",
      itemType: "video",
    },
    {
      id: "DhX_pNgz",
      image: "https://i.ytimg.com/vi/5z6IKnYXqFM/mqdefault.jpg",
      channelTitle: "The Psychedelic Muse",
      channelId: "UCAepXw94EhaO0CZV9f5D3fQ",
      itemId: "5z6IKnYXqFM",
      name: "Sync24 - Comfortable Void [Full Album]",
      itemType: "video",
    },
    {
      id: "ZtJeAFFx",
      image:
        "https://yt3.ggpht.com/ytc/AAUvwniJ6-RupADgyZPeOf8RqQV6WKcxXHS1JS0b8lOBhg=s240-c-k-c0xffffffff-no-rj-mo",
      itemId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      name: "Jordan B Peterson",
      itemType: "channel",
    },
    {
      id: "89kIxTN_",
      image: "https://i.ytimg.com/vi/gOi3FQ0R5fM/mqdefault.jpg",
      channelTitle: "Cosmic Soundwaves",
      channelId: "UC1PtAfzqXQJGvGCEMAwT30Q",
      itemId: "gOi3FQ0R5fM",
      name: "Sync24 - Ambient Archive [1996​-​2002] [Full Album]",
      itemType: "video",
    },
    {
      id: "jwcZF1wy",
      image: "https://i.ytimg.com/vi/3QMvfdXRbm4/mqdefault.jpg",
      itemId: "PLrz8hHdG8-5BaFU3C8-klOA4L6ws-Lw_b",
      name: "Sync24 - Source | Leftfield Records [Full Album]",
      channelTitle: "Chill Space",
      channelId: "UCNHbHR2KOc851Kkb_TJ2Orw",
      itemType: "playlist",
    },
    {
      id: "JIxrlwHr",
      image: "https://i.ytimg.com/vi/CNnkAWLpOFc/mqdefault.jpg",
      channelTitle: "Psychedelic Universe",
      channelId: "UCyRw5ZEQ2mVwNKq9GnSTHRA",
      itemId: "CNnkAWLpOFc",
      name: "Sync24 - Omnious (Full Album)",
      itemType: "video",
    },
    {
      id: "LrjmodWu",
      image: "https://i.ytimg.com/vi/vtZv-1tlgzA/mqdefault.jpg",
      channelTitle: "SYNC24",
      channelId: "UCrxV2H8jBQdBxIBjQIegKmw",
      itemId: "vtZv-1tlgzA",
      name: "SYNC24 - ACIDIOUS  | Album live preview in 360",
      itemType: "video",
    },
    {
      id: "3k3Ap_Yv",
      image: "https://i.ytimg.com/vi/3mKbtXdgAYQ/mqdefault.jpg",
      channelTitle: "Scaran100",
      channelId: "UC2LArxdTecS6oIT1JELrnCg",
      itemId: "3mKbtXdgAYQ",
      name: "SYNC24 - Ambient Archive [ 1996-2002 ] full album",
      itemType: "video",
    },
    {
      id: "oUksVYvb",
      image: "https://i.ytimg.com/vi/DitkWrjzY9U/mqdefault.jpg",
      channelTitle: "MrLemilica2",
      channelId: "UC_S803Fwu2NlUiNFkPu_wLQ",
      itemId: "DitkWrjzY9U",
      name: "Sync24 - Omnious [Full Album] ᴴᴰ",
      itemType: "video",
    },
    {
      id: "GO5o7lTI",
      image: "https://i.ytimg.com/vi/c43Lx9q1TV4/mqdefault.jpg",
      channelTitle: "SpaceArt Light",
      channelId: "UCsD5tCx_pEFu7nDNA2zAIfA",
      itemId: "c43Lx9q1TV4",
      name: "Sync24 - Comfortable Void [Full Album Unmixed]",
      itemType: "video",
    },
    {
      id: "DmY-i6EL",
      image: "https://i.ytimg.com/vi/fxV2NXWkrNs/mqdefault.jpg",
      channelTitle: "Scaran100",
      channelId: "UC2LArxdTecS6oIT1JELrnCg",
      itemId: "fxV2NXWkrNs",
      name: "SYNC24 - [ Everything Will Be OK ] full album",
      itemType: "video",
    },
    {
      id: "TYshLdYJ",
      image: "https://i.ytimg.com/vi/RtkZDEOS1ZI/mqdefault.jpg",
      itemId: "PLrz8hHdG8-5BD-DPr3RgOTA_fRLH55zUD",
      name: "Sync24 - Comfortable Void | Leftfield Records [Full Album]",
      channelTitle: "Chill Space",
      channelId: "UCNHbHR2KOc851Kkb_TJ2Orw",
      itemType: "playlist",
    },
    {
      id: "57scBZDv",
      image: "https://i.ytimg.com/vi/Q7TT_U2oo3A/mqdefault.jpg",
      channelTitle: "Cosmic Soundwaves",
      channelId: "UC1PtAfzqXQJGvGCEMAwT30Q",
      itemId: "Q7TT_U2oo3A",
      name: "Sync24 - Omnious [Full Album]",
      itemType: "video",
    },
    {
      id: "lEYkwSyZ",
      image: "https://i.ytimg.com/vi/_h4wUrIZWuU/mqdefault.jpg",
      channelTitle: "The Psychedelic Muse",
      channelId: "UCAepXw94EhaO0CZV9f5D3fQ",
      itemId: "_h4wUrIZWuU",
      name: "Sync24 - Eadgyth [Full EP]",
      itemType: "video",
    },
    {
      id: "17IizBMM",
      image: "https://i.ytimg.com/vi/BWJrL212SRg/mqdefault.jpg",
      channelTitle: "Trancentral",
      channelId: "UCPvkTCeGc0U7KUL5QVcKF-w",
      itemId: "BWJrL212SRg",
      name: "Sync24 - Omnious [Full Album]",
      itemType: "video",
    },
    {
      id: "HIMzPs5d",
      image: "https://i.ytimg.com/vi/44mR0n1BJiU/mqdefault.jpg",
      channelTitle: "atomicLogic",
      channelId: "UC4ZSbfPgb_YgywZG0xLbSTQ",
      itemId: "44mR0n1BJiU",
      name: "Sync24 - Source (album edit)",
      itemType: "video",
    },
    {
      id: "4bcQl9q9",
      image: "https://i.ytimg.com/vi/xcBwxHj838A/mqdefault.jpg",
      channelTitle: "DZP Music",
      channelId: "UCcEW4SihMCGpa92wUD3vqvA",
      itemId: "xcBwxHj838A",
      name: "Sync24 - Omnious (Full Album)",
      itemType: "video",
    },
    {
      id: "ggzdiJWt",
      image: "https://i.ytimg.com/vi/p4jSJLrIwnw/mqdefault.jpg",
      channelTitle: "Downtempo Vibes",
      channelId: "UCglYDP4J2usDOlMs4XsawtA",
      itemId: "p4jSJLrIwnw",
      name: "Sync24 - Omnious [Full Album]",
      itemType: "video",
    },
    {
      id: "EGQsXVmB",
      image: "https://i.ytimg.com/vi/1CGm4TChZYQ/mqdefault.jpg",
      channelTitle: "PLUR ॐ GOA",
      channelId: "UCJUfUBXXGwv7fe3LgbjxECg",
      itemId: "1CGm4TChZYQ",
      name: "Sync24 - Omnious [Full Album]",
      itemType: "video",
    },
    {
      id: "Pdu4VpiZ",
      image: "https://i.ytimg.com/vi/NMPu2vMndLA/mqdefault.jpg",
      channelTitle: "Buzz Lightbeer",
      channelId: "UCqHvJYDGRnXvck14SEQZ8IA",
      itemId: "NMPu2vMndLA",
      name: "Sync 24 Resident Advisor Podcast",
      itemType: "video",
    },
    {
      id: "ECpCKw2-",
      image: "https://i.ytimg.com/vi/QYVRGOLR1eQ/mqdefault.jpg",
      channelTitle: "FOLD",
      channelId: "UCIRWmnDrZQeOprPJG9MFCeQ",
      itemId: "QYVRGOLR1eQ",
      name: "FOLD X Cultivated Electronics  // Sync24",
      itemType: "video",
    },
    {
      id: "IVi_zY4R",
      image: "https://i.ytimg.com/vi/p82D2C3bof8/mqdefault.jpg",
      channelTitle: "Neomorpheous90",
      channelId: "UC2FSbblNJ3bCSfkVMvdoozQ",
      itemId: "p82D2C3bof8",
      name: "Sync24 - Inadvertent [Comfortable Void 2012]",
      itemType: "video",
    },
    {
      id: "2o9_0fky",
      image: "https://i.ytimg.com/vi/mv6asLy0NWk/mqdefault.jpg",
      channelTitle: "ADDA",
      channelId: "UClQovQ0QLIP3bu9sp8RzUuw",
      itemId: "mv6asLy0NWk",
      name: "Sync24 - Sequor",
      itemType: "video",
    },
    {
      id: "v5s4Ye55",
      image: "https://i.ytimg.com/vi/6aBWXV_7Iy8/mqdefault.jpg",
      channelTitle: "Diego GM",
      channelId: "UCazHgYhMOFM_gzGS-f8UeDQ",
      itemId: "6aBWXV_7Iy8",
      name: "Sync24 - Spoon",
      itemType: "video",
    },
    {
      id: "XmiX8j1g",
      image: "https://i.ytimg.com/vi/joI6Dg1uNBY/mqdefault.jpg",
      channelTitle: "Psybrations",
      channelId: "UCEkBEbI7ME92qqjMjqvuIQA",
      itemId: "joI6Dg1uNBY",
      name: "SYNC24 - Dance of the Droids [Music Video]",
      itemType: "video",
    },
    {
      id: "NOWO8qeg",
      image: "https://i.ytimg.com/vi/zwYxhTx3ntY/mqdefault.jpg",
      channelTitle: "Chill Space",
      channelId: "UCNHbHR2KOc851Kkb_TJ2Orw",
      itemId: "zwYxhTx3ntY",
      name: "Sync24 - Source (album edit) | Chill Space",
      itemType: "video",
    },
  ],
};
